In [98]:
from math import sin
from math import exp
def f(x):
    return sin(x/5.0)* exp(x/10.0) + 5*exp(-x/2.0)

In [99]:
def st(x, n):
    return [ x ** i for i in range(n+1)]

Многочлен 1-ой степени

In [100]:
import numpy as np
a = np.array([st(1, 1), st(15,1)])
b = np.array([f(1), f(15)])
x = np.linalg.solve(a, b)
print a, b, x

[[ 1  1]
 [ 1 15]] [ 3.25221687  0.63522142] [ 3.43914511 -0.18692825]


Многочлен 2-ой степени

In [101]:
a = np.array([st(1, 2), st(8, 2), st(15,2)])
b = np.array([f(1), f(8), f(15)])
x = np.linalg.solve(a, b)
print a, b, x

[[  1   1   1]
 [  1   8  64]
 [  1  15 225]] [ 3.25221687  2.31617016  0.63522142] [ 3.32512949 -0.06531159 -0.00760104]


Многочлен 3 степени

In [102]:
a = np.array([st(1, 3), st(4, 3), st(10, 3), st(15,3)])
b = np.array([f(1), f(4), f(10), f(15)])
x = np.linalg.solve(a, b)
print a, b, x

[[   1    1    1    1]
 [   1    4   16   64]
 [   1   10  100 1000]
 [   1   15  225 3375]] [ 3.25221687  1.74684595  2.50541641  0.63522142] [ 4.36264154 -1.29552587  0.19333685 -0.00823565]


In [103]:
file = open('submisson-2.txt', 'a')
for i in range(3):
    file.write(str(round(x[i], 2)))
    file.write(' ')
file.write(str(round(x[3], 2)))
file.close()